server {
    listen 80;
    listen [::]:80;
    server_name timecode-lab.ru www.timecode-lab.ru boom-kadr.217-149-24-234.nip.io;

    root /var/www/boom-kadr;
    index index.html;

    location ^~ /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(css|js|webp|png|jpg|jpeg|svg|woff|woff2)$ {
        expires 7d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}
